#!/usr/bin/env spang2
# @endpoint https://rdfportal.org/sib/sparql
# @option -a

PREFIX up: <http://purl.uniprot.org/core/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?uniprot ?mnemonic ?pathway
WHERE {
  ?uniprot up:mnemonic ?mnemonic ;
      up:annotation [
          a up:Pathway_Annotation ;
          rdfs:seeAlso ?pathway
      ] .
}
